(()=>{'use strict';
const BOOKS=window.WEBENET_BOOKS||[];
const symbols={'Horror':'☾','Action & Adventure':'↗','Romance':'♡','Mystery & Thriller':'⌕','Fantasy':'✧','Science Fiction':'✺','Literary Classics':'❧','Young Adult':'✳','Personal Growth':'◈','Business & Finance':'▤','History & Biography':'⌛','Kids & Family':'✿'};
const categories=Object.keys(symbols);const $=(id)=>document.getElementById(id);const money=(n)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={category:'all',term:'',sort:'featured',favoritesOnly:false,limit:12,cart:read('webenet_cart',{}),favorites:read('webenet_favorites',[])};
function read(k,fallback){try{return JSON.parse(localStorage.getItem(k))??fallback}catch(_){return fallback}}function save(){try{localStorage.setItem('webenet_cart',JSON.stringify(state.cart));localStorage.setItem('webenet_favorites',JSON.stringify(state.favorites))}catch(_){}}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function changeCategory(category){state.category=category;state.term='';state.limit=12;state.favoritesOnly=false;$('searchInput').value='';render();$('collection').scrollIntoView({behavior:'smooth',block:'start'})}
function buildGenres(){$('genreGrid').innerHTML=categories.map(c=>`<button class="genre-card" data-category="${safe(c)}"><span class="genre-symbol">${symbols[c]}</span><span><span class="genre-title">${safe(c)}</span><small>12 books →</small></span></button>`).join('');}
function buildFilters(){let cats=['all',...categories];$('filters').innerHTML=cats.map(c=>`<button class="filter-pill ${state.category===c?'active':''}" data-category="${safe(c)}">${c==='all'?'All books':safe(c)}</button>`).join('');document.querySelectorAll('[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===state.category&&!state.favoritesOnly));}
function filterBooks(){let matches=BOOKS.filter(b=>(state.category==='all'||b.category===state.category)&&(!state.favoritesOnly||state.favorites.includes(b.id))&&(`${b.title} ${b.author} ${b.category}`.toLowerCase().includes(state.term.toLowerCase())));if(state.sort==='title')matches.sort((a,b)=>a.title.localeCompare(b.title));else if(state.sort==='price-low')matches.sort((a,b)=>a.price-b.price);else if(state.sort==='price-high')matches.sort((a,b)=>b.price-a.price);return matches}
function coverMarkup(b){return `<div class="book-cover" data-cover-id="${b.id}"><span class="cover-prompt">${safe(b.title)}<small>${safe(b.author)}</small><span class="cover-loading">Cover loads online</span></span><img alt="Book cover for ${safe(b.title)}" loading="lazy" decoding="async" /><span class="flag">${b.priceStatus==='sourced'?'Source checked':'Reader pick'}</span><button class="wish ${state.favorites.includes(b.id)?'active':''}" data-wish="${b.id}" aria-label="Save ${safe(b.title)}">${state.favorites.includes(b.id)?'♥':'♡'}</button></div>`}
function bookCard(b){return `<article class="book-card">${coverMarkup(b)}<div class="info"><span class="book-cat">${safe(b.category)}</span><button class="book-title" data-detail="${b.id}">${safe(b.title)}</button><p class="book-author">${safe(b.author)}</p><div class="price-row"><div><strong>${money(b.price)}</strong><small>${b.priceStatus==='sourced'?'Price reference · source checked':'Estimated reference price'}</small></div><button class="plus" data-add="${b.id}" aria-label="Add ${safe(b.title)} to bag">+</button></div></div></article>`}
function render(){buildFilters();const matches=filterBooks();$('catalogTitle').innerHTML=state.favoritesOnly?'Your <em>saved reads</em>':state.category==='all'?(state.term?'Search <em>results</em>':'Discover the <em>collection</em>'):`${safe(state.category)} <em>books</em>`;$('catalogSubtitle').textContent=state.term?`${matches.length} matching titles for “${state.term}”`:state.favoritesOnly?`${matches.length} saved books`:`${matches.length} real books ${state.category==='all'?'across 12 genres':'in this section'}`;$('emptyState').hidden=matches.length!==0;
const container=$('bookContainer');if(state.category==='all'&&!state.term&&!state.favoritesOnly&&state.sort==='featured'){
 container.innerHTML=categories.map(c=>{const group=matches.filter(b=>b.category===c).slice(0,4);return `<section class="shelf-section"><div class="shelf-header"><h3>${symbols[c]} ${safe(c)} <small>12 titles</small></h3><button class="text-button" data-category="${safe(c)}">View all 12 →</button></div><div class="book-grid">${group.map(bookCard).join('')}</div></section>`}).join('');
}else{container.innerHTML=`<div class="book-grid">${matches.slice(0,state.limit).map(bookCard).join('')}</div>${matches.length>state.limit?`<button class="load-more" id="loadMore">Load more books (${matches.length-state.limit} remaining) ↓</button>`:''}`}
loadVisibleCovers();updateCounts()}
function findBook(id){return BOOKS.find(b=>b.id===id)}
function updateCounts(){let count=Object.values(state.cart).reduce((a,n)=>a+n,0);$('cartCount').textContent=count;$('favoritesCount').textContent=state.favorites.length;$('drawerCount').textContent=`(${count})`}
function add(id){state.cart[id]=(state.cart[id]||0)+1;save();updateCounts();toast('Added to your reading bag ✓');if($('cartDrawer').classList.contains('open'))renderCart()}
function wish(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(s=>s!==id):[...state.favorites,id];save();render();toast(state.favorites.includes(id)?'Saved to your favorites ♡':'Removed from your favorites')}
function openCart(){renderCart();$('overlay').hidden=false;$('cartDrawer').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function renderCart(){const items=Object.entries(state.cart).filter(([id,n])=>n>0&&findBook(id));$('cartList').innerHTML=items.length?items.map(([id,n])=>{let b=findBook(id);let src=coverMemory[id]||'';return `<div class="cart-item"><img class="cart-thumb" alt="${safe(b.title)}" src="${safe(src||'assets/webenet-logo.webp')}"><div class="cart-info"><strong>${safe(b.title)}</strong><small>${safe(b.author)}</small><div class="cart-qty"><button data-qty="${id}" data-by="-1" aria-label="Decrease quantity">−</button>${n}<button data-qty="${id}" data-by="1" aria-label="Increase quantity">+</button></div></div><div class="cart-price">${money(n*b.price)}<button class="remove" data-remove="${id}">Remove</button></div></div>`}).join(''):`<div class="cart-empty"><span>♧</span><h3>Your bag is waiting for a story.</h3><p>Discover a book you love and add it here.</p></div>`;$('subtotal').textContent=money(items.reduce((t,[id,n])=>t+findBook(id).price*n,0));$('checkoutBtn').disabled=!items.length;updateCounts()}
function close(){ $('overlay').hidden=true;$('cartDrawer').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true');$('bookModal').classList.remove('open');$('bookModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function detail(id){const b=findBook(id);if(!b)return;let src=coverMemory[id]||'assets/webenet-logo.webp';$('modalContent').innerHTML=`<div class="modal-content"><div class="modal-cover"><img alt="Cover of ${safe(b.title)}" src="${safe(src)}"></div><div class="modal-info"><div class="eyebrow">${safe(b.category)}</div><h2>${safe(b.title)}</h2><p class="modal-author">By ${safe(b.author)}</p><p>Discover this title in the WEBENET catalog. Cover artwork is supplied by Open Library when available. Check the linked publisher or retailer for edition details.</p><span class="modal-price">${money(b.price)}</span><p class="modal-price-note">${b.priceStatus==='sourced'?'Listed price from external source; may change.':'Illustrative estimated price — not verified for a specific edition.'}</p>${b.sourceUrl?`<a class="modal-source" href="${safe(b.sourceUrl)}" target="_blank" rel="noopener">Check price and edition at source ↗</a>`:''}<button class="btn primary full" data-add="${id}">Add to bag +</button><a class="modal-source" href="https://openlibrary.org/search?q=${encodeURIComponent(b.title+' '+b.author)}" target="_blank" rel="noopener">View book information on Open Library ↗</a></div></div>`;$('overlay').hidden=false;$('bookModal').classList.add('open');$('bookModal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
// Genuine external covers are requested lazily for visible cards; we never render a generic, incorrect image as a real cover.
const coverMemory=read('webenet_cover_cache',{});const queue=[];const queued=new Set();let inFlight=0;let observer=null;
function normalized(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function acceptable(doc,b){let d=normalized(doc.title);let t=normalized(b.title);return d===t||((d.startsWith(t)||t.startsWith(d))&&Math.min(d.length,t.length)>5)}
function setCover(id,url){coverMemory[id]=url;try{localStorage.setItem('webenet_cover_cache',JSON.stringify(coverMemory))}catch(_){}document.querySelectorAll(`[data-cover-id="${id}"]`).forEach(el=>{let im=el.querySelector('img');if(!im)return;im.onload=()=>{im.classList.add('loaded');el.classList.add('has-image')};im.onerror=()=>{im.src='';im.classList.remove('loaded');el.classList.remove('has-image');const note=el.querySelector('.cover-loading');if(note)note.textContent='Cover temporarily unavailable'};im.src=url})}
async function fetchCover(b){if(coverMemory[b.id]){setCover(b.id,coverMemory[b.id]);return}if(b.isbn){setCover(b.id,`https://covers.openlibrary.org/b/isbn/${b.isbn}-M.jpg?default=false`);return}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);try{
 const url='https://openlibrary.org/search.json?'+new URLSearchParams({title:b.title,author:b.author,fields:'title,author_name,cover_i',limit:'5'});
 const res=await fetch(url,{signal:controller.signal});if(!res.ok)throw Error('Open Library unavailable');const data=await res.json();const doc=(data.docs||[]).find(d=>d.cover_i&&acceptable(d,b)&&(!d.author_name||d.author_name.some(a=>normalized(a).includes(normalized(b.author).slice(0,7)))));if(doc){setCover(b.id,`https://covers.openlibrary.org/b/id/${doc.cover_i}-M.jpg`);return}
 throw Error('No available matching cover');
}catch(_){try{const google='https://www.googleapis.com/books/v1/volumes?'+new URLSearchParams({q:`intitle:${b.title} inauthor:${b.author}`,maxResults:'5',printType:'books'});const response=await fetch(google);if(!response.ok)throw Error('Google Books unavailable');const result=await response.json();const match=(result.items||[]).find(item=>{let v=item.volumeInfo||{};return acceptable(v,b)&&v.imageLinks&&(v.imageLinks.thumbnail||v.imageLinks.smallThumbnail)&&(!v.authors||v.authors.some(a=>normalized(a).includes(normalized(b.author).slice(0,7))))});if(!match)throw Error('No matching Google Books cover');let img=match.volumeInfo.imageLinks.thumbnail||match.volumeInfo.imageLinks.smallThumbnail;setCover(b.id,img.replace(/^http:/,'https:'));}catch(_){document.querySelectorAll(`[data-cover-id="${b.id}"] .cover-loading`).forEach(n=>n.textContent='Cover requires internet')}}finally{clearTimeout(timer)}}
async function pump(){while(inFlight<3&&queue.length){const b=queue.shift();inFlight++;fetchCover(b).finally(()=>{inFlight--;pump()})}}
function enqueue(b){if(queued.has(b.id))return;queued.add(b.id);queue.push(b);pump()}
function loadVisibleCovers(){if(observer)observer.disconnect();observer='IntersectionObserver'in window?new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){const b=findBook(e.target.dataset.coverId);if(b)enqueue(b);observer.unobserve(e.target)}})},{rootMargin:'180px'}):null;document.querySelectorAll('[data-cover-id]').forEach(el=>{let url=coverMemory[el.dataset.coverId];if(url){setCover(el.dataset.coverId,url)}else if(observer){observer.observe(el)}else{enqueue(findBook(el.dataset.coverId))}})}
document.addEventListener('click',e=>{const target=e.target.closest('[data-category],[data-nav],[data-add],[data-detail],[data-wish],[data-qty],[data-remove],[data-close],#loadMore');if(!target)return;
 if(target.dataset.category){changeCategory(target.dataset.category);return}if(target.dataset.nav){if(target.dataset.nav==='all'||categories.includes(target.dataset.nav))changeCategory(target.dataset.nav);return}if(target.dataset.add){add(target.dataset.add);return}if(target.dataset.detail){detail(target.dataset.detail);return}if(target.dataset.wish){wish(target.dataset.wish);return}if(target.dataset.qty){let id=target.dataset.qty;state.cart[id]=Math.max(0,(state.cart[id]||0)+Number(target.dataset.by));if(!state.cart[id])delete state.cart[id];save();renderCart();return}if(target.dataset.remove){delete state.cart[target.dataset.remove];save();renderCart();return}if(target.dataset.close!==undefined){close();return}if(target.id==='loadMore'){state.limit+=12;render();return}});
$('cartBtn').addEventListener('click',openCart);$('overlay').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('searchInput').focus()}});
$('favoritesBtn').addEventListener('click',()=>{state.favoritesOnly=!state.favoritesOnly;state.category='all';state.term='';$('searchInput').value='';render();$('collection').scrollIntoView({behavior:'smooth'});if(state.favoritesOnly)toast('Showing saved books')});$('searchInput').addEventListener('input',e=>{state.term=e.target.value.trim();state.category='all';state.limit=12;state.favoritesOnly=false;render()});$('sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render()});$('clearFilters').addEventListener('click',()=>changeCategory('all'));
$('shopNow').addEventListener('click',()=>$('collection').scrollIntoView({behavior:'smooth'}));$('browseGenres').addEventListener('click',()=>$('genres').scrollIntoView({behavior:'smooth'}));$('featureBrowse').addEventListener('click',()=>$('collection').scrollIntoView({behavior:'smooth'}));$('helpNav').addEventListener('click',()=>$('contact').scrollIntoView({behavior:'smooth'}));$('checkoutBtn').addEventListener('click',()=>toast('Demo storefront: configure a secure checkout before launch.'));
buildGenres();render();
})();
